### ISSUE TITLE
部分代码不高亮

### ISSUE THREAD

**Issue by LiarrDev** [lmm214/gridea-theme-breek#1]
目前测试只有 JS 代码是可以高亮的，C 和 Java 都没有高亮。

且在代码块不标记语言的情况下（比如，命令实在想不到该用什么语言来标记它），为白底黑字，不太美观，希望能改进。

**Comment by lmm214** [comment]
prism.min.js ，更多高亮可以自行添加样式

**Comment by LiarrDev** [comment]
> prism.min.js ，更多高亮可以自行添加样式

从 Prism 官网中下载了全量 JS 和 CSS 替换后依然不行，是否需做其他处理？

**Comment by lmm214** [comment]
main.less 第6146行默认有 PrismJS 的 css 样式代码，按需修改下
