### ISSUE TITLE
不知道为什么，我不能应用主题，选择主题后gridea没反应

### ISSUE THREAD

**Issue by Raymomen** [lmm214/gridea-theme-breek#16]

**Comment by Raymomen** [comment]
如图，好像不能识别，也不能点预览
![无标题](https://user-images.githubusercontent.com/69082662/89121778-751a7b80-d4f4-11ea-9eff-74a73030a2ad.png)

**Comment by lmm214** [comment]
`breek` 是这个子文件夹放入主题文件夹

**Comment by Raymomen** [comment]
可以了，感谢~
