### ISSUE TITLE
是否默认会创建一个首页的菜单？

### ISSUE THREAD

**Issue by LiarrDev** [lmm214/gridea-theme-breek#2]
因为 Gridea 默认情况下会创建 4 个菜单：

![Gridea 默认菜单](https://s2.ax1x.com/2019/11/27/QpZWef.png)

我也没去修改它，但是接入主题后发现会多出一个首页的菜单：

![主题菜单](https://s2.ax1x.com/2019/11/27/QpZdeK.png)

是主题创建的吗？感觉有些多余。

**Comment by lmm214** [comment]
主题自带了一个“首页”会加高亮下划线，把客户端菜单里的首页删除即可
