### ISSUE TITLE
列表条目之间的换行导致编号和内容错行

### ISSUE THREAD

**Issue by ghysrc** [lmm214/gridea-theme-breek#4]
我是用其他软件写好，然后复制到 Gridea 里面发布，其中的有序列表和无需列表复制过去在 Gridea 客户端显示正常，但预览到 breek 主题上就错行了。
Gridea Markdown 源码：
![image](https://user-images.githubusercontent.com/4082752/75084091-b592c800-5558-11ea-9177-0b69f07a8d66.png)
Gridea 客户端预览：
![image](https://user-images.githubusercontent.com/4082752/75084105-c7746b00-5558-11ea-83df-319b1fdc4086.png)
breek 主题预览：
![image](https://user-images.githubusercontent.com/4082752/75084112-dc50fe80-5558-11ea-90eb-525ef2c91fd8.png)
本来是列表行之间的回车，却出现在了列表序号的后面。breek 主题很漂亮，希望大佬有时间可以优化一下，感谢。

**Comment by lmm214** [comment]
本地测试无误，来个在线文章链接

**Comment by ghysrc** [comment]
> 本地测试无误，来个在线文章链接

你看一下：https://ghysrc.github.io/post/list/
我仔细对比了一下，可能还是复制到 Gridea 的时候有出入。我是用 Mark Text 来写的，然后复制到 Gridea 里面。在 Mark Text 里面列表条目之间的换行是这样的：
![image](https://user-images.githubusercontent.com/4082752/75105531-6ed3c980-564f-11ea-8a47-8d6437f0ff85.png)
复制到 Gridea 里面空行看光标出现了缩进：
![image](https://user-images.githubusercontent.com/4082752/75105600-5d3ef180-5650-11ea-8d3d-a34319fdad1f.png)
在 Gridea 编辑和预览都没影响，试过其他主题也可以，使用 Breek 时就必须把条目之间的空行删掉才可以。

**Comment by lmm214** [comment]
`list-style-position: inside;`
在main.less搜索以上代码，有两处，直接删除
