### ISSUE TITLE
搜索功能有问题哦

### ISSUE THREAD

**Issue by MiChongGET** [lmm214/gridea-theme-breek#5]
我打了控制台看到发现代码出错了，现在搜索功能没法实现呐
![image](https://user-images.githubusercontent.com/15011479/75174379-712b4600-576b-11ea-8aef-8282e93c6ebd.png)

**Comment by lmm214** [comment]
主题增加了一个自定义字段 site.customConfig.featureImage
重启下客户端，进：主题--自定义，保存

**Comment by MiChongGET** [comment]
请问一下，在自定义里面怎么设置呢？
![image](https://user-images.githubusercontent.com/15011479/75330362-edcd3a00-58bb-11ea-8955-7b688a713861.png)

**Comment by lmm214** [comment]
直接保存，客户端会自动生成这个空字段
