### ISSUE TITLE
手机浏览器适配

### ISSUE THREAD

**Issue by sorakoala** [lmm214/gridea-theme-breek#6]
使用手机uc浏览器，qq浏览器，手机自带浏览器打开博客，拖到最底部，博客背景色看到一个明显分层，强迫症看着难受
![QQ图片20200304024013](https://user-images.githubusercontent.com/59096776/75808134-8b939e00-5dc1-11ea-916d-fe8cf7c1aac7.jpg)
但使用手机版谷歌浏览器不会出现这种情况
![QQ图片20200304024021](https://user-images.githubusercontent.com/59096776/75808203-ad8d2080-5dc1-11ea-9b62-c59dab969a6f.jpg)

**Comment by lmm214** [comment]
main.less 内

```
#footer .published {
  text-align: center;
  color: rgba(255, 255, 255, .5);
  margin-bottom: 50px;
  font-size: 12px;
}
```

里的 `margin-bottom` 修改为 `padding-bottom`

**Comment by LiarrDev** [comment]
> main.less 内
> 
> ```
> #footer .published {
>   text-align: center;
>   color: rgba(255, 255, 255, .5);
>   margin-bottom: 50px;
>   font-size: 12px;
> }
> ```
> 
> 里的 `margin-bottom` 修改为 `padding-bottom`

修改后在华为手机自带的浏览器中依然会出现这种情况
