### ISSUE TITLE
Macos mojave10.14.5 Gridea 0.9.2 无法更换该主题

### ISSUE THREAD

**Issue by NormanBeta** [lmm214/gridea-theme-breek#7]
在Gridea/themes 下 git clone git clone https://github.com/lmm214/gridea-theme-breek/
更换主题后无法预览，自己敲入http://localhost:4000/  页面显示Cannot GET /
也无法同步

其他主题没有该问题

**Comment by lmm214** [comment]
把 breek 文件夹放入 themes 里

**Comment by NormanBeta** [comment]
![image](https://user-images.githubusercontent.com/28737120/77225070-e6413e00-6ba6-11ea-8656-f96a4e19aed3.png)
是在它下面的，同路径下的其他主题都能用

**Comment by lmm214** [comment]
gridea-theme-breek 里面还有个 breek 那个才是主题

**Comment by NormanBeta** [comment]
懂了 谢谢🙏
