### ISSUE TITLE
感谢作者，想问下怎样才能自己添加社交按钮呢？

### ISSUE THREAD

**Issue by moeacgx** [lmm214/gridea-theme-breek#8]
比如我想添加微博，QQ之类的，我想自己增加自定义按钮的话，需要怎样做呢？

**Comment by lmm214** [comment]
比较麻烦，可以把主题内的 fonts 上传到 https://icomoon.io/app/#/select，进一步添加导出，然后 css 里匹配，如果后台要自定义更要改 config.json 配置文件
